from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw" / "daisee" / "DAiSEE"
RAW_DATASET_DIR = RAW_DATA_DIR / "DataSet"
RAW_LABELS_DIR = RAW_DATA_DIR / "Labels"
RAW_LABELS_CSV = RAW_LABELS_DIR / "AllLabels.csv"
RAW_TRAIN_LABELS_CSV = RAW_LABELS_DIR / "TrainLabels.csv"
RAW_VALIDATION_LABELS_CSV = RAW_LABELS_DIR / "ValidationLabels.csv"
RAW_TEST_LABELS_CSV = RAW_LABELS_DIR / "TestLabels.csv"
RAW_VIDEO_DIR = RAW_DATASET_DIR
PROCESSED_DIR = DATA_DIR / "processed"
FEATURES_DIR = PROCESSED_DIR / "features"
PROCESSED_LABELS_CSV = PROCESSED_DIR / "engagement_only_labels.csv"
FEATURE_MANIFEST_CSV = PROCESSED_DIR / "feature_manifest.csv"

CHECKPOINT_DIR = BASE_DIR / "checkpoints"
MODEL_CHECKPOINT_PATH = CHECKPOINT_DIR / "engagement_gru.pt"
MODEL_CHECKPOINT_ML = CHECKPOINT_DIR / "engagement_gru_ml.pt"
SEQUENCE_LENGTH = 30
FEATURE_DIM = 90
BATCH_SIZE = 128
EPOCHS = 20
LEARNING_RATE = 3e-4
HIDDEN_SIZE = 128
DROPOUT = 0.3
VAL_RATIO = 0.2
RANDOM_SEED = 42
NUM_WORKERS = 0
DEVICE = "cpu"
SAMPLE_VIDEO_COUNT = 10
SAMPLE_EPOCHS = 2
WEIGHT_DECAY = 1e-4
GRAD_CLIP_NORM = 1.0
LR_SCHEDULER_PATIENCE = 2
LR_SCHEDULER_FACTOR = 0.5
EARLY_STOPPING_PATIENCE = 6

VIDEO_EXTENSIONS = (".mp4", ".avi", ".mov", ".mkv", ".mpeg", ".mpg")